server:
  port: 8081
spring:
  application:
    name: springsecurity
  datasource:
    url: jdbc:mysql://139.199.84.234:3306/taobao?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root1
    password: root1
  redis:
    host: 139.199.84.234
    port: 6379
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
mybatis-plus:
  typeAliasesPackage: com.gx.entity
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token:
  expirationSeconds: 300
  validTime: 7